### ISSUE TITLE
Paper Trailing

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/FAIRsharing-API#104]
PaperTrail is currently included in all models:

https://github.com/FAIRsharing/FAIRsharing-API/blob/master/app/models/application_record.rb#L3

This is probably overkill. Following discussion with @Drosophilic I suggest removing it from all but FairsharingRecord - this is the model where changes need to be logged. TagHistory doesn't really need it as a new tag_history is created for each edit of a fairsharing_record.

**Comment by allysonlister** [comment]
Just a basic question about this really - if we limited the PaperTrail to FairsharingRecord, then does that mean that other related objects (e.g. Publications, Licences) will not have their history maintained? Therefore, edits to a record that would add / delete a publication would be listed in the paper trail, but edits to a record that, e.g. included an update to a licence / publication would not be listed in the paper trail? 

Thanks!

**Comment by knirirr** [comment]
Any changes to relations are covered by TagHistory; PaperTrail only deals with changes to fields:

https://github.com/FAIRsharing/FAIRsharing-API/blob/master/app/models/tag_history.rb
https://github.com/FAIRsharing/FAIRsharing-API/blob/master/lib/modules/tag_history_methods.rb
https://github.com/FAIRsharing/FAIRsharing-API/blob/master/db/schema.rb#L341-L353
https://github.com/FAIRsharing/FAIRsharing-API/blob/master/app/models/fairsharing_record.rb#L6

The only reason to have PaperTrail enabled withing e.g. a licence would be if you wanted to know the history of edits to that licence in particular, e.g. changing its name or URL.

**Comment by allysonlister** [comment]
If it seems sensible to others, all relations should be included in TagHistory or similar - I note in tag_history_methods.rb that organizations, relations to other records and licences are currently missing (and as Milo has noted in his comment above).

**Comment by allysonlister** [comment]
Forgot to say that I agree that PaperTrail only needs to include FairsharingRecord. Thanks!

**Comment by knirirr** [comment]
I've been checking the code and it seems that the additional association tracking gem can handle has_many_through, which will cover the record relations case, as well as licences and organistions:

https://github.com/westonganger/paper_trail-association_tracking

...which would explain why I didn't put them in the TagHistory model.

**Comment by allysonlister** [comment]
Thank you, that's fantastic.

**Comment by knirirr** [comment]
I've moved TagHistory into a jsonb field within FairsharingRecord itself so it will be covered by the effects of PaperTrail directly. 

What do you suggest for user-defined tags, as they don't have IRIs? I could simply track their names, perhaps.

**Comment by allysonlister** [comment]
That's a great idea, thanks! And I agree we don't need anything too complex for user-defined tags. If just the names are tracked, does this mean that if I tweak a spelling of one of them that this will be tracked? Or will the change be stored as deletion of the old tag / creation of a new tag? Would prefer the former, if it isn't too difficult...

**Comment by knirirr** [comment]
I mean that in the before_save callback I'll save the names of all user_defined_tags, and nothing else. The FairsharingRecord tag_history field does not link to anything it merely notes what the state was at that time. 

Please confirm that you are happy with this and I will then be able to proceed.

**Comment by allysonlister** [comment]
Apologies for my confusion! That is great, happy with that, thanks :)
