### ISSUE TITLE
Ability to group by a in a subQuery

### ISSUE THREAD

**Issue by terazus** [FAIRsharing/FAIRsharing-API#107]
Given the following query, I would like to be able to use groupBy: "fieldName" parameter of recordAssociations like recordAssociations(groupBy: "registry").

```
{
  searchFairsharingRecords(fairsharingRegistry: "Standard" page:1 perPage: 1000) {
    totalCount
    totalPages
    records {
      recordAssociations() {
        recordAssocLabel,
        linkedRecord {
          name,
          id
        }
      }
    }
  }
}
```

The recordAssociations field should return the linked records group by registry in this context.

**Comment by knirirr** [comment]
Based on discussions with @terazus, I'll close this in favour of doing the filtering with the front-end code.
