### ISSUE TITLE
Modify the Record Query to accept new parameters

### ISSUE THREAD

**Issue by terazus** [FAIRsharing/FAIRsharing-API#109]
We should be able to query a record given an ID, a DOI or a Legacy ID.
Through the ID parameter (changed to a string) or through different parameters name.

**Comment by knirirr** [comment]
This should now provide what you need and it is available for testing. N.B., the ID argument for this query will now have to be in double quotes (GraphQL insists on typing of arguments), but the ID field for other queries will not. How much of a problem would this inconsistency be?

**Comment by terazus** [comment]
great tx
