### ISSUE TITLE
Relationships between FairsharingRecords

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/FAIRsharing-API#11]
At the time of writing the various labels available are defined here:

https://github.com/FAIRsharing/FAIRsharing-API/blob/master/app/models/record_association.rb#L15-L22

Following discussions, the plan is that more relations will be added, according to the following plan:

- All should be active, i.e. "A affects B" rather than "A is affected by B". 
- They should not number more than about 20, ideally the fewer the better.
- Some might be grouped into "similar" relationships for ease of searching. 

So, further thought is necessary to confirm what these relations will be.

**Comment by Drosophilic** [comment]
Here are the relationships. These are still in draft form but almost complete. I am working on definitions and checking whether they are sufficient in all cases.

1. Maintains (organisations to record)
2. Funds (organisations to record)
3. Collaborates on (organisations to record)
4. Controls (organisation to sub-organisation) ?
5. Implemented by/complies with standard (databases)
         6. Accepts/Accepted by (databases to models/formats)
         7. Outputs/Outputted by (databases to models/formats) - related to data access, licensing etc.
8. Related to (standards to standards, databases to databases)
         9. Shares code (databases to databases)
        10. Shares data (databases to databases)
        11. Profile of (standard to standard). This will be two records linked through the relationship “is a profile of”.
        12. Is an extension of (standard to standard) e.g. MIAME and MIAME-Tox
        13. ‘Is expressed as’ (standard to standard)
14. Recommends/Recommended by (policies to databases/standards)
15. Associated with (policies to policies)

Indentation here indicates the relationship is a sub-relationship (e.g. 'Implemented by' is a parent to 'Accepts' so all database-standard relationships associated by 'Accepts' would be included when 'Implemented by' is selected. 

Discussion and working definitions can be found in the google doc in our Planning, specs folder in the google drive.

Is this enough to be going on with?

**Comment by knirirr** [comment]
That should be enough, though I might have to make some changes to match the first point in the initial post, either altering some labels or changing the way they're created, or both. It may be necessary to re-work the way these relations are dealt with if multiple labels are needed on a single relation. 

Organisations don't currently have any labels on their relations so 5 needs a separate ticket.

1-3 refer to a different model  (organisation_link) so I'll have to do a ticket for them as well.

**Comment by Drosophilic** [comment]
For 'Controls', parent/child relationships are sufficient, thanks.
