### ISSUE TITLE
GraphQL queries bug

### ISSUE THREAD

**Issue by terazus** [FAIRsharing/FAIRsharing-API#110]
Here are two requests which return unconsistent data:

`  searchFairsharingRecords(page: 1, perPage: 30, isRecommended:false, fairsharingRegistry:"Standard") {
    aggregations
    currentPage
    perPage
    totalCount
    totalPages
    firstPage
    records {
      id
      type
      name
      abbreviation
      registry
      domains
      subjects
      taxonomies
      recordAssociations {
        linkedRecord {
          name
          id
          registry
        }
        recordAssocLabel
      }
      status
      isRecommended
    }
  }
}`
=> should return 1 result but returns 2

`  {
  searchFairsharingRecords(page: 1, perPage: 30,
    countries:"Nantierre") {
    aggregations
    currentPage
    perPage
    totalCount
    totalPages
    firstPage
    records {
      id
      type
      name
      abbreviation
      registry
      domains
      subjects
      taxonomies
      recordAssociations {
        linkedRecord {
          name
          id
          registry
        }
        recordAssocLabel
      }
      status
      isRecommended
    }
  }
}
`
=> Should return 2 records but returns none.

**Comment by terazus** [comment]
Another query causing issues:

`{searchFairsharingRecords(  q:"F"  perPage:30  page:1 ){aggregations currentPage perPage totalCount totalPages firstPage  records{countries id type name abbreviation registry domains subjects taxonomies recordAssociations{linkedRecord{name id registry} recordAssocLabel } status isRecommended }}}`
=> Should return at least rwo results (First and Fifth records) but only returns 1

**Comment by terazus** [comment]
I will also need a more on insight on what is q exactly targetting.
Eg:

`{searchFairsharingRecords(  q:"th"  perPage:30  page:1 ){aggregations currentPage perPage totalCount totalPages firstPage  records{countries id type name abbreviation registry domains subjects taxonomies recordAssociations{linkedRecord{name id registry} recordAssocLabel } status isRecommended }}}`
=> This returns all records in the database

**Comment by terazus** [comment]
`{searchFairsharingRecords(  q:"Fif"  perPage:30  page:1 ){aggregations currentPage perPage totalCount totalPages firstPage  records{countries id type name abbreviation registry domains subjects taxonomies recordAssociations{linkedRecord{name id registry} recordAssocLabel } status isRecommended }}}`
=> should this returns **Fif**th record or is it an exact match search?

**Comment by knirirr** [comment]
It appears to be the case that the "q" parameter is case insensitive but the other parameters require an exact match, and case sensitivity had not been properly dealt with when the records were indexed. 

As for the "Fif" and similar searches (compare with "Fift") this requires a bit more investiation.

**Comment by terazus** [comment]
`{
  searchFairsharingRecords(grants: ["XYZ890", "ABC123"]) {
    aggregations
    currentPage
    perPage
    totalCount
    totalPages
    firstPage
    records {
      id
      type
      name
      abbreviation
      registry
      domains
      subjects
      taxonomies
      recordAssociations {
        linkedRecord {
          name
          id
          registry
        }
        recordAssocLabel
      }
      status
      isRecommended
    }
  }
}
`
=> returns no results but should return 2
