### ISSUE TITLE
Empty buckets in aggregations

### ISSUE THREAD

**Issue by terazus** [FAIRsharing/FAIRsharing-API#111]
`{
  searchFairsharingRecords {
    aggregations
  }
}
`
=>fields **countries** and **taxonomies** have an empty bucket with non zero count !

**Comment by knirirr** [comment]
The taxonmy problem is caused by an indexing failure (this is related to the structure of the data) and this has been corrected. The countries issue would seem to have been caused by migration and requires separate treatment:

https://github.com/ISA-tools/biosharing/issues/1323
