### ISSUE TITLE
GraphQL query BUCKET bug

### ISSUE THREAD

**Issue by terazus** [FAIRsharing/FAIRsharing-API#112]
`{searchFairsharingRecords(grants:"xxh13505-05" ){ aggregations currentPage perPage totalCount totalPages firstPage records{id type name abbreviation registry domains subjects taxonomies recordAssociations{ linkedRecord{name id registry } recordAssocLabel}status isRecommended }}}`

Returns 2 records but aggregations buckets for grants rise up to 9.

**Comment by knirirr** [comment]
This seems to be due to Searchkick - if only one keyword parameter is specified then it shows all the available values, but when more than one keyword is shown the buckets appear as expected.
Whether this is expected behaviour I do not know and will have to investigate further.

**Comment by knirirr** [comment]
No luck with the discussion here:

https://github.com/ankane/searchkick/issues/1378

I'll see about adding a hack in the relevant GraphQL search to work around this odd behaviour.

**Comment by terazus** [comment]
Indeed, for the front-end is doesn't make sense to display a facet with 280 results when there's actually only one result in the current query.
I'm now sure how this behavior make sense in the first place.
Let's try with a backend solution first, it you can't find a hack around we may be able to find a front-end hack instead.

**Comment by terazus** [comment]
This really is the strangest behavior ever. Like the following query returns no results but the publication aggregate still has items:
`{searchFairsharingRecords(isRecommended:false publications:["mark d wilkinson"," susanna-assunta sansone"," erik schultes"," peter doorn"," luiz olavo bonino da silva santos"," michel dumontier"," a design framework and exemplar metrics for fairness"," missing"," https://doi.org/10.1101/225490","vempati ud","chung c","mader c","koleti a","datar n","vidovic d","wrobel d","erickson s","muhlich jl","berriz g","benes ch","subramanian a","pillai a","shamu ce","schurer sc"," metadata standard and data exchange specifications to describe"," model"," and integrate complex and diverse high-throughput screening data from the library of integrated network-based cellular signatures (lincs)."," 10.1177/1087057114522514"," http://doi.org/10.1177/1087057114522514undefined"]){ aggregations currentPage perPage totalCount totalPages firstPage records{id type name abbreviation registry domains subjects taxonomies recordAssociations{ linkedRecord{name id registry } recordAssocLabel}status isRecommended }}}`
