### ISSUE TITLE
Licence version/name

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/FAIRsharing-API#12]
Currently, licences have a version and name field. A decision must be made on whether to remove the version field.

**Comment by Drosophilic** [comment]
After discussion with Susanna, we have decided the following fields for licences:
Licence name: (e.g. Creative Commons Attribution-ShareAlike 3.0)
License abbreivation: (e.g. CC-BY-SA 3.0)
License URL: (e.g. https://creativecommons.org/licenses/by-sa/3.0/)

So we will lose the version field, but gain the license abbreviation field (the data in the name field will have to be split out once we have made this change as the name currently includes the abbreviation in parentheses).
