### ISSUE TITLE
User account modification

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/FAIRsharing-API#122]
Users should be allowed to edit these fields:

- email address
- first name
- last name
- orcid 
- twitter
- homepage
- hide email

Changes needed:

Some validation of the ORCID value will have to take place on the server to make sure the ID given maches the email address of the user. 

The username should not be changed except by admins and should be excluded from the parameters.

**Comment by knirirr** [comment]
Concerning ORCID, the process for gaining access to reader records is a little more complex than I think would be appropriate for a record validation step:

https://members.orcid.org/api/tutorial/read-orcid-records#readlim

If I understand it correctly, users would need to sign in with ORCID in order to have us validate their account.  I therefore suggest making orcid_id a read-only field for users, which will be populated by the system when they sign in with ORCID, or could be updated by curators. Therefore, there would be no need to validate it as they wouldn't be supplying it themselves. This would mean delaying the adding nof ORCID IDs to new accounts until we work on the authentication (so, not long).

Any thoughts, @Drosophilic , @terazus ?

**Comment by Drosophilic** [comment]
Sounds sensible @knirirr, thanks.
