### ISSUE TITLE
Add a MaintenanceRequestType to the GraphQL endpoint.

### ISSUE THREAD

**Issue by terazus** [FAIRsharing/FAIRsharing-API#123]
So that we can target records fields in the maintenanceRequest of the "user" query

**Comment by knirirr** [comment]
This is functioning, but something has broken https://github.com/2fd/graphdoc such that attempts to regenerate the documentation cause: `✗ Unexpected HTTP Status Code 501 (Not Implemented) from: http://localhost:3000/graphql`. This will have to be investigated separately.
