### ISSUE TITLE
searchFairsharingRecords default search

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/FAIRsharing-API#127]
The current default order seems to be the primary key of the records. If possible, this ought instead to be by the Elasticsearch best match (_score).

**Comment by knirirr** [comment]
This has now been added and deployed to the test server.
Of course, the _score sort option won't do anything unless q is specified.

**Comment by hoseinmirian** [comment]
@knirirr may it come with a better naming? like best-match

**Comment by knirirr** [comment]
I think I'll leave it as it is in the back end (_score is the term used by SearchKick) but please feel free to put an appropriate label such as best match on the UI button.
