### ISSUE TITLE
There are records with reverseRecordAssociations to themselves

### ISSUE THREAD

**Issue by ramGranell** [FAIRsharing/FAIRsharing-API#132]
The current record with id 12 (see attached image) appear with several references to itself in the field reverseRecordAssociation. I checked it at the DB and in the DB it seems just related to the standard that appears in recordAssociation.
![pasted_image](https://user-images.githubusercontent.com/39826987/79870170-7b1f9d00-83da-11ea-98af-b59c514e95ef.png)

**Comment by knirirr** [comment]
I've checked this on the same migration you're using:

```
r = FairsharingRecord.find(12)
r.relations_with_info(reverse: true).collect {|x| x.fairsharing_record_id}
=> [1462, 1616, 1798, 2018, 2032, 2083, 2447, 2563, 2690]
r.relations_with_info.collect {|x| x.fairsharing_record_id}
=> [12]
```

So, this is all looking correct.
What's going on is that the webpage is displaying links in the same way when they should be different, which will mean that @terazus will have to modify that. Here's an example recordAssociation from this case:

```#<RecordAssociation id: 23, fairsharing_record_id: 12, linked_record_id: 1228, created_at: "2020-04-15 11:13:24", updated_at: "2020-04-15 11:13:24", record_assoc_label_id: 5>
```

All RecordAssociations are directional, with fairsharing_record linking to linked_record. Although running the query with `reverse: true` will find all records that link to a record, to identify them one would have to look at the value of fairsharing_record_id in the relevant RecordAssociation - linked_record_id will always be that of the record making the reversed query.

**Comment by knirirr** [comment]
Now fixed in the front end by @terazus.
