### ISSUE TITLE
Problem with record_association back/front-end communication

### ISSUE THREAD

**Issue by ramGranell** [FAIRsharing/FAIRsharing-API#133]
@terazus  detected that all the records associations that appear in record_association relationship  are assigned as standards, e.g. the attached image
![stndard2](https://user-images.githubusercontent.com/39826987/79961545-c8554a80-847e-11ea-8a2d-0997e1e3b399.png)

However, for this example I query the DB:
id = FairsharingRecord.where("metadata->>'abbreviation' LIKE 'ABCD'")).ids[0]  RecordAssociation.where(linked_record: id).each do |a|
     puts "#{a}"
end 
id=614
and I found that there are 7 associations with other registers in which the record is in the field linked_record, e.g. RecordAssociation(fairsharing_record: 2933, linked_record: 614, record_assoc_label: 12) . Later, I check the type of this record:
RecordType.find(FairsharingRecord.where(id: '2933')[0].record_type_id).name 
=> 'collection'

I don't know why is labelled as standard in the front-end as the image indicates. @knirirr do you think is a problem of communication between back and fron-end?

**Comment by knirirr** [comment]
I don't know what the cause of this problem is. However, I can say that the data do seem to be correct when I query them. For example, the RecordAssociation you give comes up as:

```
"id": 8560,
              "fairsharingRecord": {
                "id": 2933,
                "name": "TDWG Biodiversity Information Standards",
                "registry": "collection"
              }
```

Any thoughts, @terazus ?
