### ISSUE TITLE
DOI for grants

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/FAIRsharing-API#19]
Based on this tweet, it seems though we will need to add a DOI field to the grant model:

https://twitter.com/SusannaASansone/status/1130898077982834689

**Comment by Drosophilic** [comment]
I would hesitate before adding anything to do with DOIs to grants. Our grant information is of low quality at present and I think it will be time before an international standard for grant DOIs is accepted. We should just keep an eye on this for now.

**Comment by knirirr** [comment]
OK. In that case this can be closed and I'll revisit it should any further developments occur.
