### ISSUE TITLE
Admin page permitted fields 

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/FAIRsharing-API#29]
This commit adds some permitted fields to the RecordAssociation model:

https://github.com/FAIRsharing/FAIRsharing-API/commit/44059d0bfff41bfc49cd1fefdc5436fb35bfc6c7#diff-a1eb923bc34a3232cfb9e434d3f187c9

All other Admin models will need configuring similarly.

**Comment by ramGranell** [comment]
From the code of the current commitment, I am aware of the following errors:

- (ticket #31) specific code jsonb type fields need to be included in app/admin/fairsharing_records.rb
 app/admin/fairsharing_registries.rb and app/admin/record_types.rb

-(ticket #30) there are problems of validation in some places such as http://localhost:3000/admin/domains/ when trying to edit some domains and save them having the following error:
↳ app/models/concerns/expandable.rb:100:in `loop_detection'

-there are problems when editing users  http://localhost:3000/admin/users
