### ISSUE TITLE
admin_notes: new table in the model?

### ISSUE THREAD

**Issue by ramGranell** [FAIRsharing/FAIRsharing-API#55]
In the specifications of the fields curator_notes/admin_notes (google doc  https://docs.google.com/document/d/1_1HAhrpYw9EUJat0v5L556q4KJtJ9LvjTtRSmcKH3hw/edit#heading=h.osxk43erekm9 ), they define them that include:
-text
-time stamp
-URLs
-relationship to specified curator.

Therefore, I was wondering if the correct way to implement it is to create a table in the model called:
AdminNotes
with fields 
-text
-time stamp
-URLs
and a link to User

**Comment by knirirr** [comment]
Yes, we'd need a separate model for this, though IIRC the latest requirement would be for it to be called CuratorNotes.

**Comment by Drosophilic** [comment]
Hi both,
Two points, drawing from our discussion earlier today:

- @knirirr is correct, this should be called 'CuratorNotes'
- I don't think we need to over-complicate this and create another table. I think we can handle time/datestamps and curator initials as we do now, e.g initialsDateBackward = pm20190820. URLs may be used in the text but do not need to be separated.

Does that help simplify this?

**Comment by knirirr** [comment]
Currently, these notes are simply a text field which is part of the FairsharingRecord model:

https://github.com/FAIRsharing/FAIRsharing-API/blob/master/db/schema.rb#L120

As such, you can put any text in you like and there's not really anything that can be done with display other than to put the entire thing on the screen as is. If all you need is such a simple text field then there shouldn't be any need to change anything, and this ticket may be closed.
