### ISSUE TITLE
User roles

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/FAIRsharing-API#6]
Following on from #5, user roles need to be dealt with, probably with something like https://github.com/CanCanCommunity/cancancan. 

Current plans:
- Users should be able to edit any record they have created or of which they are the maintainer, and should be able to add new user-defined tags. They should not be able to add anything else.

However:
- Should users be able to add other records not maintained by them as related, collected, and so on? Do they need a maintainers' permission for this?
- Should there be any relationship between users and organisations?

These matters need further thought (and perhaps splitting out to a separate ticket) before proceeding with anything other than the most basic roles mentioned above.

**Comment by Drosophilic** [comment]
Hi Milo, here's my 2 cents:

- Should users be able to add other records not maintained by them as related, collected, and so on? Do they need a maintainers' permission for this?

Users should be able to add relationships between records, e.g. standard X (owned by user) is implemented by database Y (not owned by user)

Users should be able to add a comment/suggestion (as now), when they think a record or relationship needs to be added/updated for records that they don't maintain, e.g. standard X (not owned by user) is implemented by database Y (not owned by user)


- Should there be any relationship between users and organisations?

Yes, so users can be associated with an organisation. This should be optional.

**Comment by knirirr** [comment]
User and curator roles should be sufficient so I'll close this.
