### ISSUE TITLE
Legacy IDs

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/FAIRsharing-API#66]
Currently, these are in the model:

https://github.com/FAIRsharing/FAIRsharing-API/blob/master/db/schema.rb#L111

Is this something that ought to be in the metadata instead, or is attempting to hide/deprecating it (by leaving it where it is) preferable?

**Comment by Drosophilic** [comment]
What would the advantages/disadvantages be of moving these to the metadata? 
The only one I see is that this would allow people who download the metadata to more easily see these, but I don't see that alone as a good reason.

**Comment by knirirr** [comment]
That is the only reason I can think of. If you think there's any particular need for users to have that then I could move the field there, otherwise there's not really much point and this ticket could be closed.
