### ISSUE TITLE
Do fields abbreviation and URL need to be mandatory for Licenses?

### ISSUE THREAD

**Issue by ramGranell** [FAIRsharing/FAIRsharing-API#71]
Currently in the table license there are as mandatory the fields name, URL and abbreviation.
In the old database there are some licenses that do not have URLs such as "Academic use", "Data available on request","Fee for commercial use".
About abbreviation, it would need to be manually curated but there are licenses that do not have any abbreviation such as the previous ones.

@allysonlister @Drosophilic, do you think, we can remove the obligation that URL and abbreviation need to appear for each license?

**Comment by Drosophilic** [comment]
I think we can remove the abbrev field (as @allysonlister says, we are currently including abbreviations in the license string anyway) and make the URL field optional.

**Comment by knirirr** [comment]
It would appear that the licence model has only been modified in the GraphQL field for https://github.com/FAIRsharing/FAIRsharing-API/commit/dee587738e34044ff48b5295bc97e51428393cb4 - it will also need changing in the schema and app/models/licence.rb.
