### ISSUE TITLE
'Previously known as' feature for resource names

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/FAIRsharing-API#73]
In addition to the resource name, please can each standard/database/policy also store an optional list of strings representing the names the resource was previously known as? This should be editable by maintainers/admin, and viewable.

This references https://github.com/ISA-tools/biosharing/issues/1286 (visible only to project members)

**Comment by ramGranell** [comment]
@allysonlister do you want it to be called alternative_names or previous_names?

**Comment by allysonlister** [comment]
Thanks, it should be called previous_names.

**Comment by ramGranell** [comment]
Ok, it is created. I also added the field in the reference document about the data model (FAIRsharing Draft Model).
