### ISSUE TITLE
In branch db_migration test failing

### ISSUE THREAD

**Issue by ramGranell** [FAIRsharing/FAIRsharing-API#75]
The test TagHistoryTest#test_new_history_is_created [ test/models/tag_history_test.rb] is failing for branch db_migration.
After   record = FairsharingRecord.create(metadata: metadata, record_type: record_types(:model))
it returns 2 versions in the branch in master it returns 0

**Comment by knirirr** [comment]
I had this test fail recently due to modifying metadata after a FairsharingRecord.create - changing metadata, even without a save, caused extra record history to be created.

**Comment by knirirr** [comment]
This is fixed, plus there shouldn't be an attempt to read the seed files on Travis.
