### ISSUE TITLE
Does abbreviation need to be a manatory field for the records?

### ISSUE THREAD

**Issue by ramGranell** [FAIRsharing/FAIRsharing-API#76]
Question to the curators: @allysonlister  and @Drosophilic 
Currently, the field abbreviation (it indicates the short-name of a record) is mandatory. There are around 100 records that do not have anything for this field, and therefore, it will need to be manually curated to put something in this field. It is also possible changing this field to optional. What do you think is the best solution?
Thank you.

**Comment by Drosophilic** [comment]
Yes, this field can/should be optional. Thanks for spotting this @ramGranell.
