### ISSUE TITLE
Problem with the migration of records: \u0000

### ISSUE THREAD

**Issue by ramGranell** [FAIRsharing/FAIRsharing-API#78]
I am not able to find what the problem is when I create the records in the branch db_migration ( 
rake db:reset RAILS_ENV=test ) that returns "\u0000". If I remove the last line or change the order of the records (file fairsharing_records) there are sometimes that the error does not occur.

**Comment by knirirr** [comment]
As the issue seems to have been addressed by recent changes in the db_migration branch I'll close this.
