### ISSUE TITLE
Requirement for a grant for a funding relationships

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/FAIRsharing-API#79]
At present a funding relationship between organisation and record requires the presence of a grant. Should this be altered so that organisations can fund without a grant?

**Comment by Drosophilic** [comment]
Yes.
So:
- Organisations can 'fund' without a grant
- All entries surrounding grants should be associated with an organisation and at least one FAIRsharing record.

Does that make sense?

**Comment by knirirr** [comment]
I'm not sure about the latter point. Do you mean that you do not want a Grant to be created unless it is associated with both an Organisation and a FairsharingRecord? If so then I will have to add a validation that it must have at least one OrganisationLink associated with it.

**Comment by knirirr** [comment]
The association of Grant-> Organisation -> FairsharingRecord is here:

https://github.com/FAIRsharing/FAIRsharing-API/blob/master/app/models/grant.rb#L6-L7

I'll modify that to give a minimum number of relations.

**Comment by knirirr** [comment]
Whilst attempting to deal with this I note that at present only curators are permitted to create, update or delete grants. Is this correct, or should users be able to do so? If the answer is that users should be able to do so then a new ticket will be needed due to the complexity of checking ownership of the organisation and grant.

**Comment by allysonlister** [comment]
Users (specifically, owners of records) are currently allowed to create grants in the old system. As long as @Drosophilic agrees, I think this behaviour should be retained. Thanks very much!

**Comment by Drosophilic** [comment]
Yes, maintainers of records should be able to add/create grants. Thanks
