### ISSUE TITLE
users with the same email address

### ISSUE THREAD

**Issue by ramGranell** [FAIRsharing/FAIRsharing-API#81]
@Drosophilic @allysonlister ,

at the moment, in the new data model, it is not possible to create two users with the same email. Do you want to keep this (easy and more practical solution that most of the online services perform), or do you want to be possible to create a user with multiple email addresses?

In the old Fairsharing, there are just eight times that there are more than user with repeated email. I don't say here who they are but you know at least three of them. Therefore, I think that the logical is to have one email, one user and also remember that you now we have established different roles with different levels of privileges.

**Comment by allysonlister** [comment]
While I would generally be happy with this, I do have one thought. I would like curators to be able to have views of the data that allow them to access FAIRsharing as a curator or as any of the other roles provided by users (e.g. log in as a standard user, a standard curator, an admin etc).

For example, an admin could log in either with full admin access or as if they just have a "standard" user account. This enables all sorts of testing to happen. Currently this is done by having multiple accounts that could be linked to the same email. I don't mind if we only allow "one account - one email", but in this case it would be nice if the system would allow us to log in and select the role we wish to log in as, too.

@Drosophilic may well override this - I'm not tied to any one methodology, just would like the functionality :-) Thanks!

**Comment by Drosophilic** [comment]
Hi @ramGranell - I think we should have one user, one email as a general rule. 

However, as @allysonlister points out, those users with full privileges may need to test functionality with fewer privileges. 

I think that the decision over system to choose, either the 'simple', one account, one set of privileges method that we have now, which will result in multiple accounts (with differing privileges) for a few people; or one account, with the ability to view the website at differing levels of privileges (or roles), is ultimately a technical one, so I'm looping in @knirirr and @terazus to hear their thoughts too.

**Comment by knirirr** [comment]
If you want to test functionality with a different privilege then a separate account would be my preferred answer.

**Comment by allysonlister** [comment]
We would need to decide, therefore, if multiple accounts could use the same email address, or alternatively require curators to use an alternative email account for their other roles.

**Comment by knirirr** [comment]
Email addresses are unique and I intend for them to remain so.
N.B. users may use their username (also unique) or email address to log in.

**Comment by ramGranell** [comment]
For testing functionality, we can have a dummy user account that you know the details to login.

**Comment by Drosophilic** [comment]
Thanks for the input @knirirr .
So, as I understand it (and I may have personal bias here as it is my preferred option):

We should allow multiple accounts as long as:
     a. They have unique usernames and email addresses (as this is just good practice)
     b. However, they could have the same personal names, organisations etc., so it's clear they are the same person (if someone wants it to be clear).

This will result in the same situation as now, where certain people will have more than one account. I think this is fine, as long as those accounts have a use, e.g. have different privileges. 

Of course, we should remove any accounts that are dormant as people forgot they had an account or somehow got locked out.

Does that answer your question @ramGranell ?

**Comment by ramGranell** [comment]
Ok, @Drosophilic , therefore email and user are unique for user, and about names and organisations we are not performing any check. Occasionally, we can check if there are multiple users with repeated names if you want.

**Comment by Drosophilic** [comment]
Hi @ramGranell - thanks, we may occasionally want to review multiple users etc., so it's good to know we could do this when required.
