### ISSUE TITLE
Missing field for Domains

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/FAIRsharing-API#90]
According to the following document, Domains ought to contain an inSubset=FAIRsharing term.

https://github.com/FAIRsharing/domain-ontology/blob/master/RequiredAnnotationProperties.md

Following discussion with @allysonlister I'll created this as a boolean term ("in_fairsharing") in order to make the various exclusions slightly easier to handle e.g. in the front end.

**Comment by allysonlister** [comment]
BTW just an added note that the inSubset annotation is optional, and if set to "FAIRsharing", it means that this term should be visible to users editing and searching records. Details in the md file @knirirr linked to. Thanks!
