### ISSUE TITLE
is pubmed need to be mandatory a number?

### ISSUE THREAD

**Issue by ramGranell** [FAIRsharing/FAIRsharing-API#92]
Hoi @Drosophilic  and @allysonlister, 

Is pubmed always a number? If so, we can put this requirement that allows to detect when someone put an incorrect pubmed in the system and avoiding future errors. In the old system, we can find pubmeds such as:
 10.1371/journal.pone.0201939
  NARDBIssue2012
  ?term=12824428
  //www.ncbi.nlm.nih.gov/pubmed/27496599

**Comment by allysonlister** [comment]
PubMed identifiers are always numbers. DOIs are a mixture. :-)
