### ISSUE TITLE
Record approval timestamp

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/FAIRsharing-API#96]
Each FairsharingRecord should have a timestamp which may be updated by anyone with permission to edit the record, to indicate that they have reviewed it. 
Records approved more than a year ago should be listed in the curator dashboard.
Hopefully it should be possible to find out who changed this field by means of PaperTrail.

**Comment by allysonlister** [comment]
Just to be clear, there is a difference between approving a record (accepting the submission by a user) and reviewing a record (stating that the record is up to date). AFAIK this ticket is to allow update of some kind of "last edited" or "last reviewed" timestamp (I'm not sure of the correct terminology within the new system) without actually needing to edit the record itself. 

And yes, records edited/reviewed more than a year ago should be listed in the curator dashboard.

thanks!

**Comment by knirirr** [comment]
This timestamp is to note that a revewer has reviewed a record. Of course, changing it will also involve saving the record, which will also update the modification date on the record. 
Are you likely to require knowledge of who reviewed it and when, e.g. a list of review dates and reveiewers? Or, is simply the date of when it was last reviewed sufficient?

**Comment by allysonlister** [comment]
Thanks @knirirr 

I would like to know a list of review dates and reviewers, but if @Drosophilic feels this is a step too far, I am happy to just have the date of last review.

**Comment by knirirr** [comment]
If a history of reviews is likely to be desired then I'll create a separate RecordReview class, linked to User and FairsharingRecord, which will keep track of each time a user has reviewed a record and each time a record has been reviewed. Any record with no reviews newer than a year can be flagged to curators. Please confirm if this is desired (e.g. @Drosophilic).

**Comment by Drosophilic** [comment]
I'm not sure if we need so much detail. I would suggest simply the date it was last reviewed by a curator or the maintainer is sufficient. 

@allysonlister - what would the benefit be of knowing who? (the when would be found in the timestamp)

@knirirr - would the 'who' not be recorded as the timestamp is updated (as reviewing would involve saving the record), so we would know who and when the record was last reviewed but not who reviewed it (and when) before then, right?

**Comment by knirirr** [comment]
@Drosophilic If you need to know who changed the timestamp then it would involve writing some logic in the code that looks at the timestamp and attempts to find an edit which occurred at the same time and happens to include the right sort of change. Anything that involves looking at previoius edits and trying to work out what was going on is not going to be trivial; they are complex. 

An alternative is to create a RecordReview which links to record and user and contains the date it was created; the record's time stamp would therefore not be altered. I think this is preferable.

**Comment by allysonlister** [comment]
Thanks - the reason for knowing who was simply to mirror what we would know from each edit... Seemed to make sense. @knirirr 's idea of a record review object sounds good. Happy to go with consensus...

**Comment by Drosophilic** [comment]
Thanks @knirirr.
Let's go with your RecordReview idea.

**Comment by knirirr** [comment]
I've added this; the GraphQL endpoint will show all reviews if requested when viewing a FairsharingRecord.
